# -*- coding: utf-8 -*-
"""python_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19MX9BQ2Qtm6sQRrxyau-XZyieKXhp4wY
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

mdyn=np.loadtxt('./dynamic.csv',delimiter=',',skiprows=1)
mbola=np.loadtxt('./bola.csv',delimiter=',',skiprows=1)
mthrougput=np.loadtxt('./throughput.csv',delimiter=',',skiprows=1)



X=np.linspace(1,634,77)

plt.figure()
plt.plot(X,mdyn[:,0]*750 ,'g--', label = "Bitrate")

plt.plot(X,mdyn[:,1]*17 ,'r--', label = "Buffer")

plt.plot(X,mdyn[:,2] ,'b--', label = "Throughput")
plt.legend()

plt.figure()
plt.plot(X,mbola[:,0]*4700 ,'g--', label = "Bitrate")

plt.plot(X,mbola[:,1]*121 ,'r--', label = "Buffer")

plt.plot(X,mbola[:,2] ,'b--', label = "Throughput")
plt.legend()

X=np.linspace(0,634,76)



X=np.linspace(0,634,77)

plt.figure()
plt.plot(X,mthrougput[:,0]*4000 ,'g--', label = "Bitrate")

plt.plot(X,mthrougput[:,1]*116 ,'r--', label = "Buffer")
plt.plot(X,mthrougput[:,2] ,'b--', label = "Throughput")

plt.legend()



metrices_dynamic=np.loadtxt('./dynamic.csv',delimiter=',',skiprows=1)

segment_dynamic=np.loadtxt('./dynamic.csv',delimiter=',',skiprows=1)
segment_bola=np.loadtxt('./bola.csv',delimiter=',',skiprows=1)
segment_throughput=np.loadtxt('./throughput.csv',delimiter=',',skiprows=1)

len(segment_dynamic)

X=np.linspace(0,77,77)

plt.figure()
plt.plot(X,segment_dynamic[:,0]/1000 ,'g--', label = "Segment Download time")
plt.plot(X,segment_dynamic[:,1] ,'r--', label = "Segment size")
plt.legend()

X=np.linspace(1,77,77)

plt.figure()
plt.plot(X,segment_bola[:,0]/1000 ,'g--', label = "Segment Download time")
plt.plot(X,segment_bola[:,1] ,'r--', label = "Segment size")
plt.legend()

len(segment_throughput)

X=np.linspace(0,77,77)

plt.figure()
plt.plot(X,segment_throughput[:,0]/1000 ,'g--', label = "Segment Download time")
plt.plot(X,segment_throughput[:,1] ,'r--', label = "Segment size")
plt.legend()



